Fix url scope regex wrong argument name.
Ostorlab/agent_openvas pull request #33
Opened 2023-01-23 16:51 UTC by deadly-panda

2023-01-23 17:14 UTC, 3asm requested changes

2023-01-23 17:14 UTC, 3asm commented on agent/openvas_agent.py
> +        domain_in_scope = re.match(self._scope_domain_regex, domain)
Missing unit test.

2023-01-24 11:23 UTC, deadly-panda commented on tests/openvas_agent_test.py
> +    """Ensure the domain scope argument is enforced, and services with domains not in the scope not should be processed."""
```suggestion
    """Ensure the domain scope argument is enforced.
    Services with domains not in the scope not should be processed."""
```

2023-01-24 17:44 UTC, 3asm approved these changes

2023-01-24 17:45 UTC, merged